/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        space:   '#070A11',
        panel:   '#121822',
        surface: '#0F1520',
        cyan:    '#00F2FF',
        nred:    '#FF3E3E',
        ngreen:  '#00FF88',
        norange: '#FF6B00',
        npurple: '#7000FF',
        npink:   '#FF00A8',
        amber:   '#FFB800',
        dim:     '#4A6070',
        bright:  '#E8F4FF',
      },
      fontFamily: {
        mono:    ['"JetBrains Mono"', '"Share Tech Mono"', 'monospace'],
        display: ['Orbitron', 'monospace'],
        ui:      ['Rajdhani', 'sans-serif'],
      },
      animation: {
        'float':        'float 3s ease-in-out infinite',
        'pulse-slow':   'pulse 3s ease-in-out infinite',
        'scan':         'scan 3s linear infinite',
        'radar':        'radar 6s linear infinite',
        'flicker':      'flicker 4s ease-in-out infinite',
        'warp':         'warp 2s linear infinite',
        'ticker':       'ticker 25s linear infinite',
        'border-flow':  'borderFlow 4s linear infinite',
        'contaminate':  'contaminate 2s ease-in-out infinite',
        'bob':          'bob 0.5s ease-in-out infinite alternate',
        'walk-l':       'walkL 0.35s ease-in-out infinite alternate',
        'walk-r':       'walkR 0.35s ease-in-out infinite alternate',
        'ring-spin':    'ringSpin 5s linear infinite',
        'data-up':      'dataUp 1s ease-in-out infinite',
        'node-ping':    'nodePing 2s ease-out infinite',
        'sidebar-glow': 'sidebarGlow 3s ease-in-out infinite',
      },
      keyframes: {
        float:       { '0%,100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-6px)' } },
        scan:        { '0%': { transform: 'translateY(-100%)' }, '100%': { transform: 'translateY(100vh)' } },
        radar:       { from: { transform: 'rotate(0deg)' }, to: { transform: 'rotate(360deg)' } },
        flicker:     { '0%,100%': { opacity: 1 }, '92%': { opacity: 1 }, '93%': { opacity: 0.3 }, '96%': { opacity: 1 } },
        warp:        { '0%': { left: '-40%', opacity: 0 }, '10%': { opacity: 1 }, '90%': { opacity: 1 }, '100%': { left: '110%', opacity: 0 } },
        ticker:      { from: { transform: 'translateX(100vw)' }, to: { transform: 'translateX(-100%)' } },
        borderFlow:  { from: { backgroundPosition: '0% 50%' }, to: { backgroundPosition: '200% 50%' } },
        contaminate: { '0%,100%': { boxShadow: '0 0 6px #FFB800' }, '50%': { boxShadow: '0 0 18px #FFB800, 0 0 32px rgba(255,184,0,0.3)' } },
        bob:         { from: { transform: 'translateY(0)' }, to: { transform: 'translateY(-3px)' } },
        walkL:       { from: { transform: 'rotate(-18deg)' }, to: { transform: 'rotate(18deg)' } },
        walkR:       { from: { transform: 'rotate(18deg)' }, to: { transform: 'rotate(-18deg)' } },
        ringSpin:    { from: { transform: 'rotate(0deg)' }, to: { transform: 'rotate(360deg)' } },
        dataUp:      { '0%': { height: 0, opacity: 0 }, '50%': { opacity: 1 }, '100%': { height: '40px', opacity: 0 } },
        nodePing:    { '0%': { transform: 'scale(1)', opacity: 0.8 }, '100%': { transform: 'scale(2.5)', opacity: 0 } },
        sidebarGlow: { '0%,100%': { opacity: 0.3 }, '50%': { opacity: 0.9 } },
      },
      backgroundImage: {
        'grid-cyan':   'linear-gradient(rgba(0,242,255,0.04) 1px, transparent 1px), linear-gradient(90deg, rgba(0,242,255,0.04) 1px, transparent 1px)',
        'grid-space':  'linear-gradient(rgba(0,242,255,0.07) 1px, transparent 1px), linear-gradient(90deg, rgba(0,242,255,0.07) 1px, transparent 1px)',
      },
      backgroundSize: {
        'grid-sm': '20px 20px',
        'grid-md': '40px 40px',
      },
    },
  },
  plugins: [],
}
